name: test

on:
  pull_request:
    branches: [ web-components-step-* ]

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-github-pages:
    name: e2e github pages test
    if: github.event.pull_request.base.ref == 'web-components-step-5'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: yarn install
      - name: Run e2e tests
        run: yarn test
      - name: Run cypress test
        run: start-server-and-test 'http-server -c-1 dist --silent' 8080   'cypress run --config baseUrl=https://carbon-design-system.github.io/carbon-for-ibm-dotcom-tutorial/step-4/'
  e2e:
    name: e2e tests
    if: github.event.pull_request.base.ref != 'web-components-step-5'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: yarn install
      - name: Build project
        run: yarn build
      - name: Run e2e tests
        run: yarn test
